// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruckLibrary.Core.DataContext;

#nullable disable

namespace TruckLibrary.Core.Migrations
{
    [DbContext(typeof(TruckLibraryDbContext))]
    [Migration("20250902082714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("TruckLibrary.Domain.Models.Truck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChassisCode")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturingPlant")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ManufacturingYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trucks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            ChassisCode = "FH1234567",
                            Color = "Red",
                            ManufacturingPlant = "Brazil",
                            ManufacturingYear = 2025,
                            Model = "FH"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            ChassisCode = "FM2345678",
                            Color = "Blue",
                            ManufacturingPlant = "Sweden",
                            ManufacturingYear = 2025,
                            Model = "FM"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ChassisCode = "VM3456789",
                            Color = "White",
                            ManufacturingPlant = "United States",
                            ManufacturingYear = 2025,
                            Model = "VM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
